[package]
authors = ["Victor Koenders <victor.koenders@gmail.com>"]
edition = "2018"
name = "smtp_server_core"
version = "0.1.0"

[dependencies]
bytes = "0.4"
failure = "0.1"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
