[package]
authors = ["Victor Koenders <victor.koenders@gmail.com>"]
edition = "2018"
name = "ui2"
version = "0.1.0"

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", rev = "33ebfcbe5e5fe4dda97a9cadd1e6bb4e9483018a" }

